# Generated by Django 3.1 on 2020-08-26 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='productcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('Icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='productsupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('id_number', models.IntegerField()),
                ('date_added', models.DateField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('number_in_stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.productcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.productsupplier')),
            ],
        ),
    ]
