# Generated by Django 3.1 on 2020-09-10 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=datetime.datetime(2020, 9, 10, 8, 55, 14, 765883, tzinfo=utc), upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
